name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Android SDK
        uses: android/setup-android@v2
        with:
          target-api: 32

      - name: Detekt
        run: ./gradlew detekt

      - name: Unit Test
        run: ./gradlew test
